-- Phase 4: seed showcase metadata used by category pages.
-- Safe to rerun: upserts by (domain, source_id).

insert into public.showcase_items (
  domain, source_id, name, item_type, profile, build, tags, emoji, primary_level, secondary_level, section_key, sort_order, is_active
)
values
  -- Wings (20)
  ('wings','classic-buffalo','Classic Buffalo','Butter','Spicy / Tangy','Cannabutter + hot sauce + garlic','["spicy","classic"]'::jsonb,'🌶️',2,0,'classic-core',10,true),
  ('wings','garlic-parmesan','Garlic Parmesan','Butter','Savory / Rich','Cannabutter + garlic -> toss -> parmesan finish','["garlic","creamy","classic"]'::jsonb,'🧄',0,0,'classic-core',20,true),
  ('wings','honey-bbq','Honey BBQ','Reduction','Sweet / Smoky','BBQ + honey + smoked paprika','["sweet","smoky","classic"]'::jsonb,'🍯',0,2,'classic-core',30,true),
  ('wings','lemon-pepper','Lemon Pepper Butter','Butter','Bright / Salty','Cannabutter + lemon zest + cracked pepper','["citrus","classic"]'::jsonb,'🍋',0,0,'classic-core',40,true),
  ('wings','teriyaki','Teriyaki Glaze','Reduction','Sweet / Umami','Soy + sugar + ginger -> simmer thick','["sweet","asian-style"]'::jsonb,'🫙',0,2,'classic-core',50,true),
  ('wings','mango-habanero','Mango Habanero','Reduction','Sweet Heat','Mango + habanero + vinegar','["spicy","sweet"]'::jsonb,'🥭',3,2,'spicy-bold',60,true),
  ('wings','nashville-hot','Nashville Hot Oil','Oil','Hot / Smoky','Cannabis oil + cayenne + paprika + brown sugar','["spicy","smoky"]'::jsonb,'🔥',3,1,'spicy-bold',70,true),
  ('wings','chili-crisp','Chili Crisp','Oil','Crunchy / Spicy','Cannabis oil + chili flakes + garlic + sesame','["spicy","asian-style","garlic"]'::jsonb,'🌶️',2,0,'spicy-bold',80,true),
  ('wings','cajun-butter','Cajun Butter','Butter','Spiced / Savory','Cannabutter + Cajun seasoning + garlic','["spicy","garlic"]'::jsonb,'🫑',2,0,'spicy-bold',90,true),
  ('wings','sriracha-honey','Sriracha Honey','Honey','Sweet Heat','Honey + sriracha + lime','["spicy","sweet"]'::jsonb,'🍋',2,2,'spicy-bold',100,true),
  ('wings','maple-bacon','Maple Bacon Glaze','Reduction','Sweet / Smoky','Maple syrup + bacon fat + pepper','["sweet","smoky"]'::jsonb,'🥓',0,3,'sweet-sticky',110,true),
  ('wings','brown-sugar-bourbon','Brown Sugar Bourbon','Reduction','Deep / Caramel','Brown sugar + bourbon + cannabutter','["sweet","smoky"]'::jsonb,'🥃',0,3,'sweet-sticky',120,true),
  ('wings','pineapple-ginger','Pineapple Ginger','Reduction','Tropical / Fresh','Pineapple juice + ginger + soy','["sweet","asian-style"]'::jsonb,'🍍',1,2,'sweet-sticky',130,true),
  ('wings','honey-mustard','Honey Mustard Infusion','Emulsion','Tangy / Sweet','Honey + mustard + cannabis oil','["sweet","creamy"]'::jsonb,'🍯',0,2,'sweet-sticky',140,true),
  ('wings','orange-glaze','Orange Glaze','Reduction','Citrus / Sweet','Orange juice + sugar + soy','["sweet","citrus"]'::jsonb,'🍊',0,2,'sweet-sticky',150,true),
  ('wings','korean-gochujang','Korean Gochujang','Reduction','Sweet / Funky / Spicy','Gochujang + honey + soy + garlic','["spicy","asian-style","garlic"]'::jsonb,'🇰🇷',2,1,'savory-umami',160,true),
  ('wings','garlic-soy-umami','Garlic Soy Umami','Oil','Deep / Salty','Cannabis oil + garlic + soy + sugar','["garlic","asian-style"]'::jsonb,'🧄',0,1,'savory-umami',170,true),
  ('wings','truffle-butter','Truffle Butter','Butter','Rich / Earthy','Cannabutter + truffle oil + parmesan','["creamy","garlic"]'::jsonb,'🍄',0,0,'savory-umami',180,true),
  ('wings','chimichurri','Herb Chimichurri','Oil','Fresh / Herbal','Cannabis oil + parsley + garlic + vinegar','["garlic","citrus"]'::jsonb,'🌿',0,0,'savory-umami',190,true),
  ('wings','ranch-butter','Ranch Butter Toss','Butter','Creamy / Familiar','Cannabutter + ranch seasoning + garlic','["creamy","garlic","classic"]'::jsonb,'🤍',0,0,'savory-umami',200,true),

  -- Popcorn (20)
  ('popcorn','garlic-butter','Garlic Butter','Butter','Savory / Classic','Cannabutter + garlic + parsley','["savory","garlic","classic"]'::jsonb,'🧄',0,0,'savory',10,true),
  ('popcorn','parmesan-herb','Parmesan Herb','Butter','Savory / Rich','Cannabutter + parmesan + Italian seasoning','["savory","garlic"]'::jsonb,'🧀',0,0,'savory',20,true),
  ('popcorn','ranch','Ranch Popcorn','Butter','Creamy / Tangy','Cannabutter + ranch seasoning packet','["savory","classic","creamy"]'::jsonb,'🤍',0,0,'savory',30,true),
  ('popcorn','truffle','Truffle Popcorn','Oil','Rich / Earthy','Cannabis oil + truffle oil + flaky salt','["savory","fancy"]'::jsonb,'🍄',0,0,'savory',40,true),
  ('popcorn','cheddar','Cheddar Popcorn','Butter','Cheesy / Salty','Cannabutter + cheddar powder + paprika','["savory","classic"]'::jsonb,'🧀',0,0,'savory',50,true),
  ('popcorn','buffalo','Buffalo Popcorn','Butter','Spicy / Tangy','Cannabutter + hot sauce + garlic powder','["spicy","classic"]'::jsonb,'🌶️',2,0,'spicy',60,true),
  ('popcorn','chili-lime','Chili Lime','Oil','Bright / Spicy','Cannabis oil + chili powder + lime zest + salt','["spicy","citrus"]'::jsonb,'🍋',2,0,'spicy',70,true),
  ('popcorn','cajun-spice','Cajun Spice','Butter','Bold / Smoky','Cannabutter + Cajun seasoning + garlic','["spicy","smoky"]'::jsonb,'🫑',2,0,'spicy',80,true),
  ('popcorn','sriracha','Sriracha Popcorn','Oil','Garlicky / Hot','Cannabis oil mist + sriracha powder + salt','["spicy"]'::jsonb,'🔥',3,0,'spicy',90,true),
  ('popcorn','nashville-hot','Nashville Hot','Oil','Hot / Smoky','Cannabis oil + cayenne + paprika + brown sugar','["spicy","smoky"]'::jsonb,'🌶️',3,1,'spicy',100,true),
  ('popcorn','caramel','Caramel Popcorn','Caramel','Sweet / Crunchy','Sugar + cannabutter -> caramelize -> coat + bake','["sweet","classic"]'::jsonb,'🍬',0,3,'sweet',110,true),
  ('popcorn','honey-butter','Honey Butter','Butter','Sweet / Salty','Cannabutter + honey + flaky salt','["sweet","classic"]'::jsonb,'🍯',0,2,'sweet',120,true),
  ('popcorn','cinnamon-sugar','Cinnamon Sugar','Butter','Warm / Sweet','Cannabutter + cinnamon + sugar + vanilla','["sweet"]'::jsonb,'✨',0,2,'sweet',130,true),
  ('popcorn','maple','Maple Popcorn','Caramel','Maple / Buttery','Maple syrup + cannabutter -> reduce -> coat','["sweet"]'::jsonb,'🍁',0,3,'sweet',140,true),
  ('popcorn','vanilla-bean','Vanilla Bean','Butter','Delicate / Sweet','Cannabutter + vanilla sugar + pinch of salt','["sweet","fancy"]'::jsonb,'🌸',0,2,'sweet',150,true),
  ('popcorn','chocolate-drizzle','Chocolate Drizzle','Chocolate','Indulgent / Rich','Melted chocolate + cannabis coconut oil drizzle','["sweet","chocolate"]'::jsonb,'🍫',0,3,'dessert-hybrid',160,true),
  ('popcorn','cookies-cream','Cookies & Cream','Chocolate','Creamy / Sweet','White chocolate + cannabis oil + crushed Oreos','["sweet","chocolate","creamy"]'::jsonb,'🍪',0,3,'dessert-hybrid',170,true),
  ('popcorn','peanut-butter','Peanut Butter','Butter','Nutty / Sweet','Warm PB + cannabutter + powdered sugar drizzle','["sweet","creamy"]'::jsonb,'🥜',0,2,'dessert-hybrid',180,true),
  ('popcorn','smores','S''mores Popcorn','Chocolate','Campfire / Sweet','Cannabis oil chocolate drizzle + marshmallow + graham cracker','["sweet","chocolate"]'::jsonb,'🔥',0,3,'dessert-hybrid',190,true),
  ('popcorn','salted-caramel-choc','Salted Caramel Chocolate','Chocolate','Complex / Indulgent','Caramel coat + chocolate drizzle + flaky salt','["sweet","chocolate","fancy"]'::jsonb,'🍫',0,3,'dessert-hybrid',200,true),

  -- Coffee (20)
  ('coffee','bulletproof','Bulletproof THC Coffee','Butter','Rich / Energizing','Cannabutter + hot coffee + blend','["classic","butter","keto"]'::jsonb,'☕',2,0,'classic-builds',10,true),
  ('coffee','infused-latte','Infused Oat Milk Latte','Tincture','Smooth / Creamy','Espresso + steamed oat milk + tincture','["classic","tincture","dairy-free"]'::jsonb,'🥛',1,1,'classic-builds',20,true),
  ('coffee','cold-brew','Infused Cold Brew','Tincture','Smooth / Bold','Cold brew + tincture + milk over ice','["cold","tincture","classic"]'::jsonb,'🧊',2,0,'classic-builds',30,true),
  ('coffee','infused-americano','Infused Americano','Tincture','Bold / Clean','Espresso + hot water + tincture','["classic","tincture","strong"]'::jsonb,'🖤',2,0,'classic-builds',40,true),
  ('coffee','cortado','Infused Cortado','Butter','Intense / Balanced','Espresso + small pour of cannabutter cream','["strong","butter","keto"]'::jsonb,'🔬',2,0,'classic-builds',50,true),
  ('coffee','infused-mocha','Infused Mocha','Oil','Chocolatey / Sweet','Espresso + cocoa + cannabis oil + steamed milk','["sweet","chocolate","oil"]'::jsonb,'🍫',1,2,'specialty',60,true),
  ('coffee','infused-caramel-latte','Infused Caramel Latte','Syrup','Sweet / Buttery','Espresso + infused caramel syrup + steamed milk','["sweet","syrup","caramel"]'::jsonb,'🍮',1,3,'specialty',70,true),
  ('coffee','vanilla-latte','Infused Vanilla Latte','Syrup','Smooth / Sweet','Espresso + vanilla cannabis syrup + oat milk','["sweet","syrup","classic"]'::jsonb,'🌸',1,2,'specialty',80,true),
  ('coffee','infused-irish-coffee','THC Irish Coffee','Cream','Boozy / Warming','Hot coffee + infused cream float','["classic","cream","sweet"]'::jsonb,'🥃',2,2,'specialty',90,true),
  ('coffee','espresso-tonic','Infused Espresso Tonic','Tincture','Bitter / Fizzy','Tonic water + espresso + tincture over ice','["cold","tincture","unique"]'::jsonb,'🫧',1,1,'specialty',100,true),
  ('coffee','infused-iced-coffee','Infused Iced Coffee','Tincture','Refreshing / Bold','Strong coffee + tincture + milk over ice','["cold","tincture","classic"]'::jsonb,'🧊',1,1,'iced-frozen',110,true),
  ('coffee','infused-frappuccino','Infused Frappuccino','Oil','Sweet / Frozen','Blended coffee + cannabis oil + ice + milk','["cold","sweet","oil"]'::jsonb,'🥤',1,3,'iced-frozen',120,true),
  ('coffee','golden-latte','Golden THC Latte','Oil','Earthy / Warming','Cannabis oil + turmeric + honey + oat milk','["wellness","oil","dairy-free"]'::jsonb,'✨',1,1,'wellness',130,true),
  ('coffee','infused-matcha','Infused Matcha Latte','Oil','Earthy / Sweet','Matcha + cannabis oil + steamed oat milk','["wellness","oil","dairy-free"]'::jsonb,'🍵',1,1,'wellness',140,true),
  ('coffee','infused-chai','Infused Chai Latte','Oil','Spiced / Warming','Chai concentrate + cannabis oil + steamed milk','["sweet","wellness","oil"]'::jsonb,'🌶️',1,2,'wellness',150,true),
  ('coffee','coconut-coffee','Infused Coconut Coffee','Oil','Tropical / Rich','Coffee + cannabis coconut oil + coconut milk','["keto","oil","dairy-free"]'::jsonb,'🥥',2,1,'wellness',160,true),
  ('coffee','infused-hot-chocolate','Infused Hot Chocolate','Oil','Rich / Indulgent','Hot milk + cocoa + cannabis coconut oil','["sweet","chocolate","oil"]'::jsonb,'🍫',1,3,'sweet-dessert',170,true),
  ('coffee','pumpkin-spice-latte','Infused Pumpkin Spice Latte','Syrup','Spiced / Sweet','Espresso + pumpkin cannabis syrup + steamed milk','["sweet","syrup","seasonal"]'::jsonb,'🎃',1,3,'sweet-dessert',180,true),
  ('coffee','mint-mocha','Infused Mint Mocha','Oil','Minty / Chocolate','Espresso + peppermint + cocoa + cannabis oil','["sweet","chocolate","oil"]'::jsonb,'🌿',1,2,'sweet-dessert',190,true),
  ('coffee','cinnamon-dolce','Infused Cinnamon Dolce Latte','Syrup','Warm / Sweet','Espresso + cinnamon cannabis syrup + oat milk','["sweet","syrup","seasonal"]'::jsonb,'🍁',1,2,'sweet-dessert',200,true),

  -- Fries (20)
  ('fries','garlic-butter-fries','Garlic Butter Fries','Butter','Savory / Rich','Cannabutter + garlic + parsley toss','["classic","butter","garlic"]'::jsonb,'🧄',0,0,'classic',10,true),
  ('fries','truffle-fries','Truffle Parmesan Fries','Oil','Earthy / Rich','Cannabis oil + truffle oil + parmesan finish','["fancy","oil","garlic"]'::jsonb,'🍄',0,0,'classic',20,true),
  ('fries','cheese-fries','Cannabis Cheese Sauce Fries','Butter','Cheesy / Indulgent','Cannabis cheddar sauce poured over fries','["classic","butter","creamy"]'::jsonb,'🧀',0,0,'classic',30,true),
  ('fries','ranch-fries','Cannabis Ranch Fries','Powder','Creamy / Tangy','Cannabis butter toss + ranch powder','["classic","butter","creamy"]'::jsonb,'🤍',0,0,'classic',40,true),
  ('fries','loaded-fries','Loaded Cannabis Fries','Butter','Everything / Indulgent','Cannabutter + sour cream + cheese + bacon bits','["classic","butter","creamy"]'::jsonb,'🏆',0,0,'classic',50,true),
  ('fries','cajun-fries','Cajun Cannabis Fries','Oil','Bold / Spiced','Cannabis oil toss + Cajun seasoning blend','["spicy","oil","smoky"]'::jsonb,'🫑',2,0,'spicy',60,true),
  ('fries','buffalo-fries','Buffalo Ranch Fries','Butter','Spicy / Creamy','Cannabutter buffalo sauce + ranch dipping','["spicy","butter","classic"]'::jsonb,'🌶️',2,0,'spicy',70,true),
  ('fries','spicy-mayo-fries','Spicy Cannabis Aioli Fries','Aioli','Creamy / Spicy','Cannabis oil aioli + sriracha drizzle','["spicy","aioli","creamy"]'::jsonb,'🌶️',2,0,'spicy',80,true),
  ('fries','Nashville-hot-fries','Nashville Hot Fries','Oil','Hot / Smoky','Cannabis oil cayenne sauce toss','["spicy","oil","smoky"]'::jsonb,'🔥',3,0,'spicy',90,true),
  ('fries','chili-cheese-fries','Chili Cannabis Cheese Fries','Butter','Bold / Hearty','Cannabis cheese sauce + chili over fries','["classic","butter","spicy"]'::jsonb,'🌶️',1,0,'spicy',100,true),
  ('fries','honey-sriracha-fries','Honey Sriracha Fries','Glaze','Sweet Heat','Cannabis honey + sriracha glaze','["sweet","spicy","glaze"]'::jsonb,'🍯',2,2,'specialty',110,true),
  ('fries','korean-fries','Korean Gochujang Fries','Glaze','Sweet / Funky / Spicy','Cannabis oil gochujang glaze + sesame + scallions','["spicy","asian","glaze"]'::jsonb,'🇰🇷',2,1,'specialty',120,true),
  ('fries','miso-butter-fries','Miso Butter Fries','Butter','Umami / Rich','Cannabutter + white miso toss','["asian","butter","fancy"]'::jsonb,'🫙',0,0,'specialty',130,true),
  ('fries','poutine','Cannabis Poutine','Butter','Indulgent / Rich','Cannabis gravy + cheese curds over fries','["classic","butter","creamy"]'::jsonb,'🍟',0,0,'specialty',140,true),
  ('fries','al-pastor-fries','Al Pastor Fries','Oil','Spiced / Tropical','Cannabis oil + al pastor spice + pineapple','["spicy","oil","sweet"]'::jsonb,'🍍',1,1,'specialty',150,true),
  ('fries','lemon-herb-fries','Lemon Herb Fries','Oil','Bright / Fresh','Cannabis oil + lemon zest + fresh herbs','["classic","oil","light"]'::jsonb,'🍋',0,0,'herby-fresh',160,true),
  ('fries','parmesan-rosemary-fries','Parmesan Rosemary Fries','Oil','Savory / Aromatic','Cannabis oil + rosemary + parmesan','["classic","oil","fancy"]'::jsonb,'🌿',0,0,'herby-fresh',170,true),
  ('fries','pesto-fries','Cannabis Pesto Fries','Oil','Herby / Fresh','Cannabis olive oil pesto toss + pine nuts','["fancy","oil","garlic"]'::jsonb,'🌿',0,0,'herby-fresh',180,true),
  ('fries','za-atar-fries','Za''atar Fries','Oil','Herby / Tangy','Cannabis olive oil + za''atar spice blend','["fancy","oil","light"]'::jsonb,'🌿',0,0,'herby-fresh',190,true),
  ('fries','katsu-fries','Katsu Curry Fries','Glaze','Sweet / Savory / Warm','Cannabis oil Japanese curry sauce drizzle','["asian","glaze","sweet"]'::jsonb,'🍛',1,2,'herby-fresh',200,true)
on conflict (domain, source_id) do update
set
  name = excluded.name,
  item_type = excluded.item_type,
  profile = excluded.profile,
  build = excluded.build,
  tags = excluded.tags,
  emoji = excluded.emoji,
  primary_level = excluded.primary_level,
  secondary_level = excluded.secondary_level,
  section_key = excluded.section_key,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;

